# Generated by Django 5.2.4 on 2026-07-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='cannot_be_found_in_packs',
            field=models.BooleanField(default=False, help_text='not found in /packs multipacklys', verbose_name='Cannot be Found in packs'),
        ),
    ]
