# Generated by Django 5.2.4 on 2026-07-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0010_ball_cannot_be_found_in_packs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='cannot_be_found_in_packs',
        ),
        migrations.AddField(
            model_name='ball',
            name='hidden_from_packs',
            field=models.BooleanField(default=False, help_text='If enabled, this footballer is excluded from pack draws that check this flag (currently: /packs multipackly)'),
        ),
        migrations.AddField(
            model_name='ball',
            name='hidden_from_spawn',
            field=models.BooleanField(default=False, help_text='If enabled, this footballer is excluded from /spawn, /spawnrare, and /spawnregime (including automatic wild spawns).'),
        ),
    ]
